%% plot_inner_iter_count_decay.m
% Plot the number of inner iterations per outer iteration for decay models.
% Data is generated by main_iter.py.

clearvars; close all; clc;

% Update this path if your system config / OMEGA changes.
MAT_FILE = '../sim_results/64TX_4UE_4RF/inner_iter_count_vs_outer_64_0.05.mat';

if ~isfile(MAT_FILE)
    error('File not found: %s\nRun main_iter.py first to generate it.', MAT_FILE);
end

d = load(MAT_FILE);

fig = figure('Color', 'w');
hold on; box on; grid on;

plotted_any = false;

if isfield(d, 'outer_iter_J5_decay') && isfield(d, 'inner_iter_count_J5_decay')
    plot(d.outer_iter_J5_decay(:), d.inner_iter_count_J5_decay(:), '-o', ...
        'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'UPGA J_{max}=5 (decay)');
    plotted_any = true;
end

if isfield(d, 'outer_iter_J10_decay') && isfield(d, 'inner_iter_count_J10_decay')
    plot(d.outer_iter_J10_decay(:), d.inner_iter_count_J10_decay(:), '-s', ...
        'LineWidth', 1.8, 'MarkerSize', 5, 'DisplayName', 'UPGA J_{max}=10 (decay)');
    plotted_any = true;
end

if ~plotted_any
    error(['No J5/J10 decay inner-iteration arrays found in %s. ' ...
           'Enable run_UPGA_J5_decay and/or run_UPGA_J10_decay in system_config.py.'], MAT_FILE);
end

xlabel('Outer iteration number');
ylabel('Inner iteration count');
title('Decay schedule: inner iterations vs outer iteration');
legend('Location', 'best');

out_dir = fileparts(MAT_FILE);
out_base = fullfile(out_dir, 'inner_iter_count_vs_outer_decay');

saveas(fig, [out_base '.png']);
print(fig, out_base, '-depsc', '-r300');

fprintf('Saved:\n  %s.png\n  %s.eps\n', out_base, out_base);
